
(FA)
metric space: there is a need to describe different mode of convergence, and metric space with different metric function can induce different topology, which does the work.
complete: this is a condition in (Banach fixed point theorem) and (equivalence of totally bounded and relatively compact)
compact (space): used in definition of relatively compact
sequentially compact (space): equivalent to compact in a metric space
relatively compact: condition in Arzela-Ascoli theorem
epsilon net: used in the definition of totally bounded
totally bounded: equivalent to relatively compact in a complete metric space


(DG)
regular (curve): condition so that arc parameter is well-defined
signed (curvature on plane): since in the plane two vectors are enough to define an orientation, so we can define the normal vector to keep the orientation as right-handed.


(DM)
topology space structure (ie. specification of open subsets): to describe such concepts as continuity, connectedness.
(topological) manifold: to describe locally n-dimensional objects, in the sense of Euclidean topology


(AT)
homotopy: to describe map between maps
fundamental group: detect holes
contractible (space): can shrink to a point
simply connected: those with trivial fundamental group, i.e. no holes in some sense
cone: a construction used to represent trivial homotopy, i.e. a homotopy from a map to a constant map

(A)
module: vector space over a ring
invariant subspace: analogy to orbit (under the action of a fixed linear map)
cyclic subspace: analogy to cyclic group (generated by v in the module V^T)
